name: u_credit_card
description: Credit Card UI
version: 1.0.0+5
homepage: 'https://github.com/utpal-barman/u-credit-card-flutter'

environment:
  sdk: ">=2.18.0 <3.0.0"


dependencies:
  flutter:
    sdk: flutter


dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  very_good_analysis: ">=3.1.0 <5.0.0"

flutter:
  assets:
    - assets/images/
  fonts:
    - family: ocr-a
      fonts:
        - asset: fonts/OCR-A-regular.ttf
